name: build-current

on:
  schedule:
  # 每月 4号，1:23执行一次，以同步官方
  - cron: '23 1 4 * *'
  push:
    #branches: [ master ]
    paths:
    - current/Dockerfile.alpine
    - current/Dockerfile.debian
    - docker-entrypoint.sh
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # 设置 QEMU 以支持多个平台
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # 设置 buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # 配置缓存
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      # 登录 dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 编译 Alpine 推送到 dockerhub
      - name: Build and push Alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: current/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            ryjer/hexo:current-alpine3.13
            ryjer/hexo:current-alpine

      # 编译 buster-slim 推送到 dockerhub
      - name: Build and push Buster-slim
        uses: docker/build-push-action@v2
        with:
          context: .
          file: current/Dockerfile.debian
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            ryjer/hexo:current-buster-slim
            ryjer/hexo:buster-slim
            ryjer/hexo:slim
       
      # 处理缓存无限增大问题的临时修复，以防出现问题。（等待github官方修复）
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
